# Generated by Django 4.2.7 on 2024-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0002_comp_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_det',
            name='cat',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comp_det',
            name='cnm',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='pro_comp',
        ),
    ]
