# Generated by Django 4.2.7 on 2024-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0003_comp_det_cat_alter_comp_det_cnm_delete_pro_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='comp_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=25)),
                ('psw', models.CharField(max_length=25)),
            ],
        ),
    ]
