# Generated by Django 4.2.7 on 2024-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0004_comp_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_log',
            name='cnm',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
