# Generated by Django 4.2.7 on 2024-05-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eml', models.EmailField(max_length=254)),
                ('psw', models.CharField(max_length=10)),
            ],
        ),
    ]
