# Generated by Django 4.2.7 on 2024-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_tbl',
            name='dim',
            field=models.FileField(default=1, upload_to='dpic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver_tbl',
            name='lcn',
            field=models.FileField(default=1, upload_to='license'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver_tbl',
            name='lno',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
