# Generated by Django 4.2.7 on 2024-03-18 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0004_comp_log'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.reg_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProApp.comp_det')),
            ],
        ),
    ]
