# Generated by Django 4.2.7 on 2024-03-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_pay_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnm', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('bd', models.DateField()),
                ('dd', models.DateField()),
                ('sc', models.IntegerField()),
            ],
        ),
    ]
