# Generated by Django 4.2.7 on 2024-03-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_trans_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans_tbl',
            name='dnm',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trans_tbl',
            name='vnm',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
