# Generated by Django 4.2.7 on 2024-03-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_trans_tbl_dnm_trans_tbl_vnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('goods_name', models.CharField(max_length=100)),
                ('goods_description', models.TextField()),
                ('goods_image', models.ImageField(upload_to='goods_images/')),
                ('basic', models.IntegerField()),
                ('ended', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.reg_tbl')),
            ],
        ),
    ]
