# Generated by Django 4.2.7 on 2024-03-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_auction_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=25)),
                ('gname', models.CharField(max_length=50)),
                ('basic', models.IntegerField()),
                ('st', models.DateTimeField()),
                ('et', models.DateTimeField()),
                ('mb', models.IntegerField()),
            ],
        ),
    ]
