# Generated by Django 4.2.7 on 2024-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_bid_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_tbl',
            name='et',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bid_tbl',
            name='st',
            field=models.CharField(max_length=25),
        ),
    ]
