# Generated by Django 4.2.7 on 2024-03-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_bid_tbl_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_tbl',
            name='bidder',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
