# Generated by Django 4.2.7 on 2024-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_bid_tbl_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_tbl',
            name='ex',
            field=models.CharField(max_length=25),
        ),
    ]
