# Generated by Django 4.2.7 on 2024-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnm', models.CharField(max_length=25)),
                ('dnm', models.CharField(max_length=25)),
                ('loc', models.CharField(max_length=25)),
                ('mob', models.IntegerField()),
                ('add', models.TextField()),
            ],
        ),
    ]
